name: E2E tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # At minute 0 past every 2nd hour.

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        total-shards: [5]
    steps:
      - name: Run Municipio E2E Tests
        uses: helsingborg-stad/municipio-e2e-action@v2
        with:
          sitemap-urls: ${{ vars.E2E_SITEMAP_URLS }}
          shard: ${{ matrix.shard }}
          total-shards: ${{ matrix.total-shards }}
