name: E2E Tests

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.generate_shards.outputs.shards }}
    steps:

      - name: Clone municipio-e2e-tests repository
        run: git clone https://github.com/helsingborg-stad/municipio-e2e-tests.git .

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install
      
      - name: Generate E2E shards
        id: generate_shards
        run: |
          shards=$(composer generate:shards)
          echo "Generated shards: $shards"
          echo "shards=$shards" >> "$GITHUB_OUTPUT"

  run:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        shard: ${{ fromJson(needs.setup.outputs.shards) }}
    steps:
      - name: Clone municipio-e2e-tests repository
        run: git clone https://github.com/helsingborg-stad/municipio-e2e-tests.git .

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      - name: Run E2E tests
        run: SHARD_FILE="${{ matrix.shard }}" vendor/bin/municipio-e2e-run