name: E2E Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  e2e:
    uses: helsingborg-stad/municipio-e2e-tests/.github/workflows/e2e.yml@main
    with:
      sitemaps: ${{ vars.SITEMAP_URLS }}