name: E2E Tests

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Configure GitHub authentication for Composer
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --dev
      
      - name: Generate E2E shards
        id: generate_shards
        run: |
          vendor/bin/municipio-e2e-generate-shards > shards.json
          echo "shards=$(cat shards.json | jq -c .)" >> $GITHUB_OUTPUT
  run:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        shard: ${{ fromJson(needs.setup.outputs.shards) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        
      - name: Configure GitHub authentication for Composer
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --dev

      - name: Run E2E tests
        run: SHARD_FILE="${{ matrix.shard }}" vendor/bin/municipio-e2e-run